# Site settings
title: 康熙
email: 168568123@qq.com
description: > # this means to ignore newlines until "baseurl:"
  自由自在的写让自己满意的代码.
baseurl: "http://kangjiastar.github.io/" # the subpath of your site, e.g. /blog/
url: "http://kangjiastar.github.io/" # the base hostname & protocol for your site

github_username:  KangJiastar

# Build settings
markdown: kramdown
