# Site settings
title: 康熙的技术博客
email: 168568123@qq.com
description: > # this means to ignore newlines until "baseurl:"
  代码是写出来的艺术,需要不停歇的写代码才能有更多的发现和进步.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  kangJiastar

# Build settings
markdown: kramdown
